### ISSUE TITLE
Function dropdown list not displaying correctly

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#36]
![function dropdown list bug](https://cloud.githubusercontent.com/assets/1021209/15637018/c718859e-2652-11e6-894a-1f8fb9d8f098.jpg)

**Comment by asaletourneau** [comment]
just did a test here http://jsfiddle.net/mAVpt/ and when the embed width is set to 1084, the function dropdown list does display correctly.

**Comment by asaletourneau** [comment]
This appears to possibly be a Drupal issue? I've tested with 600px wide in http://jsfiddle.net/mAVpt/  and the function dropdown list renders correctly.This is probably the same width of the embed in the Drupal page, despit that width being chosen as 1084 in the edited page embed code.

**Comment by Conal-Tuohy** [comment]
CSS from the host site is interfering. Need to set default values in provisualizer.css, with high priority, to prevent the host site's CSS applying.

**Comment by asaletourneau** [comment]
function drop-down list now displaying properly in Firefox but not in Chrome nor I.E where each function title is broken across  2 lines.

**Comment by asaletourneau** [comment]
dropdown list now displaying in all browsers **except** Chrome (Version 39.0.2171.99 m (64-bit)

**Comment by Conal-Tuohy** [comment]
On investigation, it turned out that the `<select>` element was being mucked about with by another Javascript library loaded in that page, namely [JCF - Javascript Custom Forms](http://prov.content.webplace.com.au/themes/custom/publicrecord/js/jquery.main.js?v=8.1.1); see line 1383 for the part which defines that elements with a class of "default" should be left unmolested.

Fixed in 0047e09 to add a class of "default" to the "functions" `<select>` element.

**Comment by asaletourneau** [comment]
Should I be able to see the dropdown function list display correctly now? 
I've cleared the cache in Chrome and it still doesn't display correctly 
i.e. each function title still breaking across 2 lines. See Chrome 
screnshot from 9:30 this morning:



Cheers

Asa Letourneau
Online Engagement Officer
T:  03 9348 5759  F:  03 9348 5656
asa.letourneau@prov.vic.gov.au

Public Record Office Victoria
Victorian Archives Centre | 99 Shiel St North Melbourne VIC 3051
www.prov.vic.gov.au
 (Please Note that I work from home on Mondays with no remote access.)

PROV News | http://prov.vic.gov.au/publications/blog
Events | http://prov.vic.gov.au/whats-on
Battle to Farm | http://soldiersettlement.prov.vic.gov.au/

Our offices are located on the land of the Kulin Nations. We acknowledge 
and pay our respects to the Traditional Owners, past and present. 

You must not copy, disclose, distribute, store or otherwise use this 
material without permission . Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments . The State does not accept liability in connection with 
computer viruses , data corruption, delay, interruption, unauthorised 
access or use.

**Comment by asaletourneau** [comment]
![chrome function bug](https://cloud.githubusercontent.com/assets/1021209/15693803/d5fa0b7a-27db-11e6-919b-ff54be9c5337.jpg) Apologies for this not coming through in the above comments that I emailed in reply to your github notification.

**Comment by Conal-Tuohy** [comment]
You are still seeing the select element created by JCF! Which is weird; I'm looking at the same page in Chrome right now and it's working for me. Can you give me the version of Chrome you're running there, Asa?

**Comment by asaletourneau** [comment]
Hi, running Version 39.0.2171.99 m (64-bit)      chrome://chrome/

Cheers. What version are you running? If it's working I'll scrap my 
version and install yours instead! Off to lunch.



Asa Letourneau
Online Engagement Officer
T:  03 9348 5759  F:  03 9348 5656
asa.letourneau@prov.vic.gov.au

Public Record Office Victoria
Victorian Archives Centre | 99 Shiel St North Melbourne VIC 3051
www.prov.vic.gov.au
 (Please Note that I work from home on Mondays with no remote access.)

PROV News | http://prov.vic.gov.au/publications/blog
Events | http://prov.vic.gov.au/whats-on
Battle to Farm | http://soldiersettlement.prov.vic.gov.au/

Our offices are located on the land of the Kulin Nations. We acknowledge 
and pay our respects to the Traditional Owners, past and present. 

You must not copy, disclose, distribute, store or otherwise use this 
material without permission . Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments . The State does not accept liability in connection with 
computer viruses , data corruption, delay, interruption, unauthorised 
access or use.

**Comment by Conal-Tuohy** [comment]
My Chrome version is:
Version 51.0.2704.63 (64-bit)

Your version appears to date from about January last year. It's probably a good idea to update it, yes.

**Comment by asaletourneau** [comment]
Best I could do without bothering is grab Version 39.0.2171.99 m (64-bit) 
and it actually works!!!!!! Well done Conal. It's a race to see who closes 
that issuer :) I should also conbfirm again that Help text scroll bar 
works on Macbook Pro athome but still not on ipad nor iphone and neither 
does help box drag.

Cheers





Asa Letourneau
Online Engagement Officer
T:  03 9348 5759  F:  03 9348 5656
asa.letourneau@prov.vic.gov.au

Public Record Office Victoria
Victorian Archives Centre | 99 Shiel St North Melbourne VIC 3051
www.prov.vic.gov.au
 (Please Note that I work from home on Mondays with no remote access.)

PROV News | http://prov.vic.gov.au/publications/blog
Events | http://prov.vic.gov.au/whats-on
Battle to Farm | http://soldiersettlement.prov.vic.gov.au/

Our offices are located on the land of the Kulin Nations. We acknowledge 
and pay our respects to the Traditional Owners, past and present. 

You must not copy, disclose, distribute, store or otherwise use this 
material without permission . Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments . The State does not accept liability in connection with 
computer viruses , data corruption, delay, interruption, unauthorised 
access or use.

**Comment by asaletourneau** [comment]
Okay, works on Chrome, Safari, Firefox and Internet Explorer! I should also confirm again that Help text scroll bar works on Macbook Pro but still not on ipad nor iphone and neither does help box drag.
We'll getr there!
